[package]
name = "tamako"
version = "0.1.0"
description = "Cozy anonymous whispers"
authors = ["fawn <fawn@envs.net>"]
repository = "https://github.com/fawni/tamako"
license = "OSL-3.0"
edition = "2021"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.12.0", features = ["attributes"] }

sqlx = { version = "0.6.3", features = ["sqlite", "runtime-async-std-rustls"] }

femme = "2.2.1"
serde = { version = "1.0.158", features = ["derive"] }
dotenvy = "0.15.7"

chrono = "0.4.24"
chrono-tz = "0.8.1"

nanorand = "0.7.0"
rs-snowflake = "0.6.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
