[package]
name = "tamako"
version = "1.1.0"
description = "Cozy anonymous whispers"
authors = ["fawn <fawn@envs.net>"]
repository = "https://codeberg.org/fawn/tamako"
license = "OSL-3.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }

actix-web = "4.3.1"
actix-files = "0.6.2"
actix-governor = "0.4.1"

askama = { version = "0.12.0", features = ["with-actix-web"] }
askama_actix = "0.14.0"

sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-rustls"] }

serde = { version = "1.0.183", features = ["derive"] }
femme = "2.2.1"
log = "0.4.20"
dotenvy = "0.15.7"

chrono = "0.4.26"
chrono-tz = "0.8.3"

webhook = "2.1.2"
rs-snowflake = "0.6.0"
once_cell = "1.18.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
