[package]
name = "tamako"
version = "0.1.0"
description = "Cozy anonymous whispers"
authors = ["fawn <fawn@envs.net>"]
repository = "https://github.com/fawni/tamako"
license = "OSL-3.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
tide = "0.16.0"
tide-governor = "1.0.3"

askama = { version = "0.12.0", features = ["with-tide"] }
askama_tide = "0.15.0"

sqlx = { version = "0.6.3", features = [
    "sqlite",
    "runtime-async-std-rustls",
    "offline",
] }

femme = "2.2.1"
serde = { version = "1.0.160", features = ["derive"] }
dotenvy = "0.15.7"

chrono = "0.4.24"
chrono-tz = "0.8.2"

rs-snowflake = "0.6.0"
once_cell = "1.17.1"

reqwest = { version = "0.11.16", features = ["json"] }
webhook = "2.1.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
